### PR TITLE
Fixed bug with incorrect slicing in the server side search.

### LINKED ISSUE #95: Server side search doesn't always return all results
First off, thanks for the great wrapper! As I've been using it more and more, I noticed an issue.

When getting back 4 results from server, and passing them into callback, only one ends up displayed in the suggestions. This is with a 5 suggestion limit.

I was looking through code and it seems like an issue in the async function, where suggestions are being sliced erroneously when appended. When running through the below code, rendered is initally equal to 0, suggestions.length =4, and that.limit = 5. The below code basically implies that suggestions should be sliced from 0 to (5-4 = 1) which means that only one suggestion is shown instead of all 4.

Am I missing something?

function async(suggestions) {
                    ...
                        rendered += suggestions.length;
                        that._append(query, suggestions.slice(0, that.limit - rendered));
                        ...
                }

### PR DESCRIPTION
**Pull request by Volodymyr-K**
Closes #95

### CODE REVIEW

**Comment by sergeyt** [comment]
hope this will be also fixed in typeahead.js soon

**Comment by sergeyt** [comment]
@Volodymyr-K thanks for PR!

**Comment by Volodymyr-K** [comment]
@sergeyt Thanks for merging my PR!

Can you publish a new version of your package on Atmosphere please? I'd like to switch back to an official version of the package instead of building from the source.

**Comment by sergeyt** [comment]
published new version including this PR

**Comment by Volodymyr-K** [comment]
Thanks!

**Pull request merged**
