### PR TITLE
Adding ability to override the display key (what gets puts into the input field when the user selects a match)

### PR DESCRIPTION
**Pull request by BruceHubbard**

### CODE REVIEW

**Comment by dmeneses** [comment]
Is this planned to add or already added into the last release??  I need this feature.

**Comment by sergeyt** [comment]
@dmeneses try to use `data-value-key` attribute, `data-display-key` is not supported yet, but could be a synonym to the `data-value-key`.

**Comment by dmeneses** [comment]
The problem is that in the dropdown i want to show something extra besides the value and when selected show only the value.

For example

when typing '123'
i want to show '123456789 - SomeRandomName'
and when selected 
i want to put as a value '132456789'

So only with data-value-key this is not easy to achieve.

**Comment by sergeyt** [comment]
@dmeneses your use case could be achieved without `display-key` (see issue #45), i.e. as suggestion data source you need to return (e.g. map your collection) with `id`, `value` fields and use `id` on `selected` event.

**Comment by dmeneses** [comment]
ouch... your have the reason thanks, but in my case I prefer to use the data-template. Sorry I didn't review correctly the documentation.

**Pull request closed without merging**
