### PR TITLE
compat with Meteor 3

### PR DESCRIPTION
**Pull request by dokithonon**

### CODE REVIEW

**Comment by sergeyt** [comment]
it is funny, I don't remember how to publish the package 😄

**Comment by dokithonon** [comment]
Thanks for accepting the PR. I have never published a package to packosphere or atmosphere. Maybe this can help : https://guide.meteor.com/writing-atmosphere-packages#publishing-atmosphere
meteor publish should do the work. thanks again

**Comment by sergeyt** [comment]
Yep. I'll try to publish new version today.

**Comment by dokithonon** [comment]
hello, have you been able to publish it ? Thanks a lot

**Comment by sergeyt** [comment]
got this one:
```
=> Errors while publishing:sergeyt:typeahead

While publishing the package:
error: You must specify a version constraint for package jquery
error: You must specify a version constraint for package blaze
error: You must specify a version constraint for package twbs:bootstrap
```
fixing

**Comment by sergeyt** [comment]
@dokithonon just published new version. could you please review [this PR](https://github.com/sergeyt/meteor-typeahead/pull/165). I was not using meteor for a long time 😄

**Pull request merged**
